# -*- coding: utf-8 -*-
"""Ejercicio de Gráficas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qk0ujb6BzdvlnbS67JRF6Q43QY9SbBvF
"""

import matplotlib.pyplot as plt
import numpy as np

#Grafico de lineas

x= ["Enero","Febrero","Marzo","Abril","Mayo","Junio"]
y= [25,35,66,70,105,25]
plt.plot(x,y, color ="blueviolet", marker = "o", linestyle ="-", linewidth = 2)
plt.title("Alarmas vendidas durante el primer bimestre", pad=15, fontsize=15)
plt.xlabel("Meses")
plt.ylabel("Alarmas")
plt.figtext(0.7, 0.02, "Stefania Colorado", ha="center", fontsize=12)

plt.grid()

import matplotlib.pyplot as plt

x = ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio"]
y = [25, 35, 66, 70, 105, 25]

plt.pie(y, labels=x, autopct="%1.1f%%")

plt.title("Alarmas vendidas durante el primer semestre")

plt.figtext(0.5, 0.02, "Stefania Colorado", ha="center", fontsize=12)

plt.show()